### ISSUE TITLE
Move to metakgp.org domain

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/sarathi#60]
This is to be done after #59 , #57 and #56 .

Move the domain name to metakgp.org

**Comment by icyflame** [comment]
If this is deployed on Heroku, these are the steps:

- [ ] Add the domain to the Heroku application ( Heroku application owner )
    - *Note:* This is allowed on Heroku only if you have a credit card added to your account
- [ ] Add a DNS record pointing `sarathi.metakgp.org` to the Heroku application ( @icyflame  )

**Comment by thealphadollar** [comment]
Done.
